service: default
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- warmup

instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  max_concurrent_requests: 80

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /static
  static_dir: static
  secure: always

- url: /_ah/warmup
  script: mirror.app
  secure: always

- url: /.*
  script: mirror.app
  secure: always
